### PR TITLE
Set required and default config values.

### PR DESCRIPTION
**Pull request by jmcarp**
@rogeruiz @rememberlenny

### CODE REVIEW

**Comment by rememberlenny** [comment]
You guys are crazy for these late hours.

**Comment by jmcarp** [comment]
Have to do something while I'm waiting for fire emblem to download

**Comment by rememberlenny** [comment]
Looks good from a high level. Didn't spot anything obvious, but I didn't run it either.

**Review by rogeruiz — APPROVED** [review]
👍 :shipit:

**Pull request merged**
